# NO LONGER USED!

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import pandas as pd
from fuzzywuzzy import process
from constants import KENPOM_FILE, ESPN_FILE, DATA_FILENAME, DATA_DIRECTORY

pd.set_option('expand_frame_repr', False)
pd.set_option('display.max_columns', 0)  # Display any number of columns
pd.set_option('display.max_rows', 68)  # Display any number of rows

In [8]:
# Load kenpom data that was previously scraped
kenpom = pd.read_csv(KENPOM_FILE.format(gender="mens"))

# Import 538's info
espn = pd.read_csv(ESPN_FILE)
# espn_slice = (espn['gender'] == 'mens') & (espn['forecast_date'] == max(espn['forecast_date'])) & (espn["team_alive"] == 1)
# For backdated runs
espn_slice = (espn['gender'] == 'mens') & (espn['forecast_date'] == "2023-03-15") & (espn["team_alive"] == 1)
team_info = espn[espn_slice][['team_id', 'team_name', 'team_region', 'team_seed', 'team_rating']]

In [25]:
espn[espn_slice].head()

    gender forecast_date  playin_flag  rd1_win   rd2_win   rd3_win   rd4_win   rd5_win   rd6_win   rd7_win  results_to  team_alive  team_id team_name  team_rating team_region team_seed  team_slot
544   mens    2023-03-15            0      1.0  0.971048  0.741489  0.588248  0.407247  0.309131  0.221186           1           1      248   Houston        93.22     Midwest         1         96
545   mens    2023-03-15            0      1.0  0.985787  0.819328  0.654065  0.452827  0.304873  0.161726           1           1      333   Alabama        92.57       South         1          0
546   mens    2023-03-15            0      1.0  0.921392  0.646432  0.458320  0.224546  0.141317  0.083376           1           1      251     Texas        90.08     Midwest         2        124
547   mens    2023-03-15            0      1.0  0.983293  0.693804  0.406726  0.253038  0.119743  0.052939           1           1     2509    Purdue        89.48        East         1         32
548   mens    2023-03-15            0      1.0  0.978209  0.656921  0.389981  0.202425  0.091174  0.049506           1           1     2305    Kansas        89.62        West         1         64

In [11]:
# Match Kenpom and ESPN team names
kenpom['team_id'] = np.nan
kenpom['espn_name'] = np.nan
choices = team_info['team_name'].tolist()  # Get all of the ESPN team names
for index, row in kenpom.iterrows():
    team = row['Team']
    match = process.extractOne(team, choices)  # extract the best match for every kenpom name
    if match[1] == 100:  # it's a perfect match
        espn_team_id = team_info[team_info['team_name'] == match[0]]['team_id'].values[0]
        kenpom.loc[index, 'team_id'] = espn_team_id
        choices.remove(match[0])  # remove that team as a possible choice

# Need to do this first, otherwise the >80 match ¯\_(ツ)_/¯
# kenpom.loc[kenpom['Team'] == "St. John's", 'team_id'] = 2599
# choices.remove("St. John's (NY)")
# kenpom.loc[kenpom['Team'] == "Ohio St.", 'team_id'] = 194
# choices.remove("Ohio State")

scores = {}
for index, row in kenpom[kenpom['team_id'].isna()].iterrows():
    team = row['Team']
    match = process.extractOne(team, choices)
    espn_team_id = team_info[team_info['team_name'] == match[0]]['team_id'].values[0]
    scores[team] = match, espn_team_id
    if match[1] > 80:
        kenpom.loc[index, 'team_id'] = espn_team_id
        choices.remove(match[0])  # remove that team as a possible choice

missing_kenpom = kenpom.loc[kenpom['team_id'].isna(), 'Team'].tolist()
missing_espn = team_info.loc[team_info['team_name'].isin(choices)][['team_name', 'team_id']]

print("Missing Kenpom Teams: {}".format(missing_kenpom))
print("Matching ESPN Teams:\n {}".format(missing_espn))

Missing Kenpom Teams: ['TCU', 'USC', 'VCU']
Matching ESPN Teams:
                  team_name  team_id
561        Texas Christian     2628
582    Southern California       30
588  Virginia Commonwealth     2670

In [12]:
scores

{"Saint Mary's": (("Saint Mary's (CA)", 95), 2608),
 'San Diego St.': (('San Diego State', 89), 21),
 'Utah St.': (('Utah State', 82), 328),
 'Iowa St.': (('Iowa State', 82), 66),
 'Kansas St.': (('Kansas State', 86), 2306),
 'TCU': (('Texas Christian', 30), 2628),
 'Michigan St.': (('Michigan State', 88), 127),
 'Boise St.': (('Boise State', 84), 68),
 'USC': (('Texas Christian', 60), 2628),
 'Penn St.': (('Penn State', 82), 213),
 'Miami FL': (('Miami (FL)', 95), 2390),
 'Arizona St.': (('Arizona State', 87), 9),
 'VCU': (('Texas Christian', 30), 2628),
 'N.C. State': (('North Carolina State', 86), 152),
 'Kent St.': (('Kent State', 82), 2309),
 'Charleston': (('College of Charleston', 90), 232),
 'Louisiana': (('Louisiana-Lafayette', 90), 309),
 'Montana St.': (('Montana State', 87), 147),
 'Kennesaw St.': (('Kennesaw State', 88), 338),
 'UNC Asheville': (('North Carolina-Asheville', 86), 2427),
 'Texas A&M Corpus Chris': (('Texas A&M-Corpus Christi', 96), 357)}

In [13]:
# Need to manually fix the crappy ones
manual_matches = [
    ('Loyola Chicago', 2350),
    ('VCU', 2670),
    ('USC', 30),
    ('BYU', 252),
    ('LSU', 99),
    ('TCU', 2628),
    ('UAB', 5),
]
for team, team_id in manual_matches:
    kenpom.loc[kenpom['Team'] == team, 'team_id'] = team_id

merged = pd.merge(kenpom, team_info, how='left', on='team_id')


# FIRST_FOUR_LOSERS = [
#     "Pittsburgh",
#     "Nevada",
#     "Fairleigh Dickinson",
#     "Texas A&M-Corpus Christi",
# ]
# for team in FIRST_FOUR_LOSERS:
#     merged = merged[merged['team_name'] != team]

simple = merged[['team_region', 'Seed', 'team_name', 'team_id', 'AdjustEM', 'AdjustT', 'team_rating']]

In [14]:
simple.head()

  team_region  Seed    team_name  team_id  AdjustEM  AdjustT  team_rating
0     Midwest     1      Houston    248.0     29.04     63.3        93.22
1        West     2         UCLA     26.0     27.82     66.2        88.26
2       South     1      Alabama    333.0     27.42     72.7        92.57
3        West     4  Connecticut     41.0     25.40     66.6        89.24
4        East     4    Tennessee   2633.0     24.60     65.5        86.87

In [15]:
simple.tail()

   team_region  Seed                 team_name  team_id  AdjustEM  AdjustT  team_rating
59        West    15  North Carolina-Asheville   2427.0      1.55     68.5        73.02
60     Midwest    16         Northern Kentucky     94.0      0.51     62.0        72.86
61       South    16  Texas A&M-Corpus Christi    357.0     -0.34     69.1        70.59
62        West    16                    Howard     47.0     -3.23     68.9        69.31
63        East    16       Fairleigh Dickinson    161.0    -10.79     68.7        66.93

In [16]:
simple.shape

(64, 7)

In [22]:
simple.to_csv(f"{DATA_DIRECTORY.format(gender='mens')}/kenpom_simple.csv", index=False)