In [1]:
import numpy as np
import pandas as pd
from fuzzywuzzy import process

pd.set_option('expand_frame_repr', False)
pd.set_option('display.max_columns', 0)  # Display any number of columns
pd.set_option('display.max_rows', 68)  # Display any number of rows

In [2]:
YEAR = 2022
DATA_DIRECTORY = f"data/{YEAR}"
KENPOM_FILE = f'{DATA_DIRECTORY}/kenpom_{YEAR}.csv'
ESPN_FILE = (
    'https://projects.fivethirtyeight.com/'
    f'march-madness-api/{YEAR}/fivethirtyeight_ncaa_forecasts.csv'
)
EXPORT_FILENAME = f'{DATA_DIRECTORY}/simple_{YEAR}.csv'

In [6]:
# Load kenpom data that was previously scraped
kenpom = pd.read_csv(KENPOM_FILE)

# Import 538's info
espn = pd.read_csv(ESPN_FILE)
espn_slice = (espn['gender'] == 'mens') & (espn['forecast_date'] == max(espn['forecast_date'])) & (espn["team_alive"] == 1)
# For backdated runs
# espn_slice = (espn['gender'] == 'mens') & (espn['forecast_date'] == "2022-03-16") & (espn["team_alive"] == 1)
team_info = espn[espn_slice][['team_id', 'team_name', 'team_region', 'team_seed']]

In [7]:
# Match Kenpom and ESPN team names
kenpom['team_id'] = np.nan
kenpom['espn_name'] = np.nan
choices = team_info['team_name'].tolist()  # Get all of the ESPN team names
for index, row in kenpom.iterrows():
    team = row['Team']
    match = process.extractOne(team, choices)  # extract the best match for every kenpom name
    if match[1] == 100:  # it's a perfect match
        espn_team_id = team_info[team_info['team_name'] == match[0]]['team_id'].values[0]
        kenpom.loc[index, 'team_id'] = espn_team_id
        choices.remove(match[0])  # remove that team as a possible choice

# Need to do this first, otherwise the >80 match ¯\_(ツ)_/¯
# kenpom.loc[kenpom['Team'] == "St. John's", 'team_id'] = 2599
# choices.remove("St. John's (NY)")
kenpom.loc[kenpom['Team'] == "Ohio St.", 'team_id'] = 194
choices.remove("Ohio State")

scores = {}
for index, row in kenpom[kenpom['team_id'].isna()].iterrows():
    team = row['Team']
    match = process.extractOne(team, choices)
    espn_team_id = team_info[team_info['team_name'] == match[0]]['team_id'].values[0]
    scores[team] = match, espn_team_id
    if match[1] > 80:
        kenpom.loc[index, 'team_id'] = espn_team_id
        choices.remove(match[0])  # remove that team as a possible choice

missing_kenpom = kenpom.loc[kenpom['team_id'].isna(), 'Team'].tolist()
missing_espn = team_info.loc[team_info['team_name'].isin(choices)][['team_name', 'team_id']]

print("Missing Kenpom Teams: {}".format(missing_kenpom))
print("Matching ESPN Teams:\n {}".format(missing_espn))

Missing Kenpom Teams: ['LSU', 'Loyola Chicago', 'TCU', 'USC', 'UAB']
Matching ESPN Teams:
                team_name  team_id
627      Louisiana State       99
639          Loyola (IL)     2350
644      Texas Christian     2628
645  Southern California       30
653   Alabama-Birmingham        5

In [11]:
scores

{"Saint Mary's": (("Saint Mary's (CA)", 95), 2608),
 'LSU': (('Louisiana State', 60), 99),
 'San Diego St.': (('San Diego State', 89), 21),
 'Loyola Chicago': (('Loyola (IL)', 76), 2350),
 'Murray St.': (('Murray State', 86), 93),
 'Boise St.': (('Boise State', 84), 68),
 'Colorado St.': (('Colorado State', 88), 36),
 'TCU': (('Louisiana State', 30), 99),
 'Michigan St.': (('Michigan State', 88), 127),
 'USC': (('Louisiana State', 60), 99),
 'Iowa St.': (('Iowa State', 82), 66),
 'UAB': (('Alabama-Birmingham', 60), 5),
 'Miami FL': (('Miami (FL)', 95), 2390),
 'South Dakota St.': (('South Dakota State', 91), 2571),
 'New Mexico St.': (('New Mexico State', 90), 166),
 'Montana St.': (('Montana State', 87), 147),
 'Jacksonville St.': (('Jacksonville State', 91), 55),
 'Cal St. Fullerton': (('Cal State Fullerton', 89), 2239),
 'Georgia St.': (('Georgia State', 87), 2247),
 'Norfolk St.': (('Norfolk State', 87), 2450),
 'Wright St.': (('Wright State', 86), 2750)}

In [12]:
# Need to manually fix the crappy ones
manual_matches = [
    ('Loyola Chicago', 2350),
    ('VCU', 2670),
    ('USC', 30),
    ('BYU', 252),
    ('LSU', 99),
    ('TCU', 2628),
    ('UAB', 5),
]
for team, team_id in manual_matches:
    kenpom.loc[kenpom['Team'] == team, 'team_id'] = team_id

merged = pd.merge(kenpom, team_info, how='left', on='team_id')


# FIRST_FOUR_LOSERS = [
#     "Rutgers",
#     'Bryant',
#     'Wyoming',
#     'Texas Southern',
# ]
# for team in FIRST_FOUR_LOSERS:
#     merged = merged[merged['team_name'] != team]

simple = merged[['team_region', 'Seed', 'team_name', 'team_id', 'AdjustEM', 'AdjustT']]

In [13]:
simple.head()

  team_region  Seed team_name  team_id  AdjustEM  AdjustT
0        West     1   Gonzaga   2250.0     32.95     72.5
1       South     1   Arizona     12.0     27.24     72.2
2        East     2  Kentucky     96.0     26.63     67.4
3        East     1    Baylor    239.0     26.52     67.2
4       South     5   Houston    248.0     26.51     63.9

In [14]:
simple.tail()

   team_region  Seed            team_name  team_id  AdjustEM  AdjustT
59        West    15  Cal State Fullerton   2239.0      1.91     66.0
60        West    16        Georgia State   2247.0      1.66     67.1
61        East    16        Norfolk State   2450.0      0.05     66.9
62       South    16         Wright State   2750.0     -0.34     68.7
63     Midwest    16       Texas Southern   2640.0     -0.92     68.0

In [15]:
simple.shape

(64, 6)

In [16]:
simple.to_csv(EXPORT_FILENAME, index=False)