In [1]:
%load_ext autoreload
%autoreload 2

In [1]:
import pandas as pd

In [2]:
from manual_scoring import compute_all_scores
from constants import ESPN_FILE, BRACKETS_JSON, DATA_DIRECTORY

In [4]:
espn = pd.read_csv(ESPN_FILE)
most_recent = max(espn[espn['gender'] == 'mens']['forecast_date'])
results = espn[
    (espn['gender'] == 'mens') &
    (espn['forecast_date'] == most_recent) &
    (espn['rd1_win'] == 1)
]

# Update these!
# 538 does not update after the championship game
results.loc[0, 'rd7_win'] = 1
results.loc[1, 'rd7_win'] = 0

/Users/Alex/opt/anaconda3/envs/py3/lib/python3.8/site-packages/pandas/core/indexing.py:966: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

In [5]:
TEAM_NAME = "Saint Peter's"
FILE_NAME = f"{DATA_DIRECTORY}/saint_peters_results.feather"

In [6]:
results.loc[results["team_name"] == TEAM_NAME]

,gender,forecast_date,playin_flag,rd1_win,rd2_win,rd3_win,rd4_win,rd5_win,rd6_win,rd7_win,results_to,team_alive,team_id,team_name,team_rating,team_region,team_seed,team_slot
5,mens,2022-04-02,0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,7,0,2612,Saint Peter's,80.14,East,15,62

In [7]:
%%time
compute_all_scores(results, BRACKETS_JSON, TEAM_NAME, FILE_NAME)

Completed 1000000: 1482.03
CPU times: user 3min 3s, sys: 28.6 s, total: 3min 32s
Wall time: 24min 45s

In [8]:
df = pd.read_feather(FILE_NAME)

In [9]:
df.describe()

                    8               4
count  1000000.000000  1000000.000000
mean         0.003220        0.000402
std          0.056654        0.020046
min          0.000000        0.000000
25%          0.000000        0.000000
50%          0.000000        0.000000
75%          0.000000        0.000000
max          1.000000        1.000000

In [12]:
df[["8", "4"]].sum()

8    3220
4     402
dtype: int64